services:
  backend:
    build: ./backend-service
    environment:
      - FLASK_ENV=production
    networks:
      - app-network

  frontend:
    build: ./frontend-service
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 
