apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jonny-fullstack-app-local
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JeEonPark/container-2025-final.git
    targetRevision: local
    path: k8s/local
  destination:
    server: https://kubernetes.default.svc
    namespace: jonny-local
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
