apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: jonny-local
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/jeeonpark/backend-local:a1cd7b89
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "development"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/hello
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/hello
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5 
