apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: jonny-local
  labels:
    app: backend
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/jeeonpark/backend-local:4dba864c
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "development"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "24Gi"
            cpu: "8000m"
 