apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: jonny
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
  type: ClusterIP 
