apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  # - ingress.yaml

commonLabels:
  app.kubernetes.io/name: jonny-fullstack-app
  app.kubernetes.io/version: v1.0.0

namespace: jonny
